version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    build: .
    image: pollapp:v1
    command: python manage.py runserver 0.0.0.0:8001
    volumes: 
      - .:/apps
    ports:
      - "8001:8001"
    depends_on:
      - db

