apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: centos
  name: centos
spec:
  containers:
  - command: ["sleep", "10000"]
    image: centos
    imagePullPolicy: IfNotPresent
    name: centos
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
