---
apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django-kube-app
spec:
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001
  selector:
    app: django-kube-app
    tier: app
  type: NodePort
